CastleApartments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from CastleApartments import settings
from properties import views as propview
from agents import views as agentview

urlpatterns = [
    path('', propview.index, name='index'),
    path('properties/', include('properties.urls')),
    path('clients/', include('clients.urls')),
    path('agents/', include('agents.urls')),
    path('purchases/', include('purchases.urls')),
    path('admin/', admin.site.urls),
    path('about/', agentview.about, name='about'),
    path('contact/', agentview.contact, name='contact'),
]

agents/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:id>', views.get_agent_by_id, name='agent-details')
]

agents/models.py
from django.db import models
from django.contrib.auth.models import User


class Agents(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=999, blank=True)
    image = models.CharField(max_length=999, blank=True)

    def __str__(self):
        return '{} - {} - {}'.format(self.name, self.email, self.phone)

properties/models.py
from django.db import models
from agents.models import Agents
from django.core.validators import MinValueValidator


class PropertiesDetails(models.Model):
    garden = models.BooleanField(blank=True)
    garage = models.BooleanField(blank=True)
    pets = models.BooleanField(blank=True)
    accessibility = models.BooleanField(blank=True)


class PropertiesAddress(models.Model):
    streetName = models.CharField(max_length=999)
    houseNumber = models.CharField(max_length=255)
    zipCode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

    def __str__(self):
        return '{} {}'.format(self.streetName, self.houseNumber)


class Properties(models.Model):
    type = models.CharField(max_length=255)
    size = models.IntegerField(validators=[MinValueValidator(1)])
    rooms = models.IntegerField(validators=[MinValueValidator(1)])
    price = models.IntegerField(validators=[MinValueValidator(50000)])
    yearBuilt = models.IntegerField(validators=[MinValueValidator(0)])
    description = models.CharField(max_length=999, blank=True)
    status = models.CharField(max_length=255, default='available')
    agent = models.ForeignKey(Agents, on_delete=models.CASCADE)
    address = models.ForeignKey(PropertiesAddress, on_delete=models.CASCADE)
    details = models.ForeignKey(PropertiesDetails, on_delete=models.CASCADE)


class PropertiesImages(models.Model):
    property = models.ForeignKey(Properties, on_delete=models.CASCADE)
    link = models.CharField(max_length=999)
    text = models.CharField(max_length=255, blank=True)

agents/forms/profile_update.py
from django.forms import ModelForm, widgets
from clients.models import Profile


class ProfileFormUpdate(ModelForm):
    class Meta:
        model = Profile
        exclude = ['id', 'email']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'phone': widgets.TextInput(attrs={'class': 'form-control'}),
            'description': widgets.TextInput(attrs={'class': 'form-control'}),
            'image': widgets.TextInput(attrs={'class': 'form-control'})
        }

agents/forms/send_email.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

agents/views.py
from django.shortcuts import render, get_object_or_404
from agents.models import Agents
from properties.models import Properties
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from agents.forms.send_email import ContactForm


def about(request):
    is_agent = request.user.groups.filter(name="agents").exists()
    context = {
        'agents': Agents.objects.all(),
        'is_agent': is_agent
    }
    return render(request, 'about.html', context)


def get_agent_by_id(request, id):
    is_agent = request.user.groups.filter(name="agents").exists()
    return render(request, 'agents/agent_details.html', {
        'agent': get_object_or_404(Agents, pk=id),
        'properties': Properties.objects.filter(agent=id),
        'agents': Agents.objects.exclude(id=id),
        'is_agent': is_agent
    })


def contact(request):
    is_agent = request.user.groups.filter(name="agents").exists()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['castle_apartments@hotmail.com'])
                messages.success(request, 'Success, email sent')
            except BadHeaderError:
                messages.error(request, "Something went wrong, email wasn't sent")
    return render(request, 'contact.html', {
        'form': ContactForm(),
        'is_agent': is_agent
    })

templates/agents/agent_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="site-blocks-cover overlay" style="background-image: url({{ agent.image }});" data-aos="fade"
         data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-10">
                    <span class="d-inline-block text-white px-3 mb-3 property-offer-type rounded">Agent Details for</span>
                    <h1 class="mb-2">{{ agent.name }}</h1>
                    <p class="mb-5"><strong class="h2 text-success font-weight-bold">{{ agent.description }}</strong>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section site-section-sm">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2>Managed Properties:</h2>
                    <div class="slide-one-item home-slider owl-carousel">
                        {% for property in properties %}
                            <div class="col-md-12 col-lg-12 mb-12">
                                <a id="{{ property.id }}" href="/properties/{{ property.id }}"
                                   class="prop-entry d-block">
                                    <figure>
                                        {% if property.propertiesimages_set.first.link %}
                                            <img src="{{ property.propertiesimages_set.first.link }}"
                                                 alt="{{ property.propertiesimages_set.first.text }}"
                                                 class="img-thumbnail">
                                        {% else %}
                                            <img src="https://via.placeholder.com/800x450.png?text=No+Image+Found"
                                                 alt="No Image Found" class="img-thumbnail">
                                        {% endif %}
                                    </figure>
                                    <div class="prop-text">
                                        <div class="inner">
                                            <span class="price rounded">${{ property.price }}</span>
                                            <h3 class="title">{{ property.address.streetName }} {{ property.address.houseNumber }}</h3>
                                            <p class="location">{{ property.address.city }}, {{ property.address.country }} {{ property.address.zipCode }}</p>
                                        </div>
                                        <div class="prop-more-info">
                                            <div class="inner d-flex">
                                                <div class="col">
                                                    <span>Area:</span>
                                                    <strong>{{ property.size }}m<sup>2</sup></strong>
                                                </div>
                                                <div class="col">
                                                    <span>Rooms:</span>
                                                    <strong>{{ property.rooms }}</strong>
                                                </div>
                                                <div class="col">
                                                    <span>Year Built:</span>
                                                    <strong>{{ property.yearBuilt }}</strong>
                                                </div>
                                                <div class="col">
                                                    <span>Status:</span>
                                                    <strong>{{ property.status|upper }}</strong>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2>Contact Information:</h2>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h5 class="text-dark">Name:</h5>
                            <p class="text-primary">{{ agent.name }}</p>
                        </li>
                        <li class="list-group-item">
                            <h5 class="text-dark">Email:</h5>
                            <p class="text-primary">{{ agent.email }}</p>
                        </li>
                        <li class="list-group-item">
                            <h5 class="text-dark">Phone:</h5>
                            <p class="text-primary">{{ agent.phone }}</p>
                        </li>
                    </ul>
                </div>
            </div>
            {% if agents %}
                <div class="site-section">
                    <div class="container">
                        <div class="row mb-5 justify-content-center">
                            <div class="col-md-7">
                                <div class="site-section-title text-center">
                                    {% if agent %}
                                        <h2>Other Agents</h2>
                                    {% else %}
                                        <h2>Our Agents</h2>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="row block-13">

                            <div class="nonloop-block-13 owl-carousel">
                                {% for agent in agents %}
                                    <div class="slide-item">
                                        <a href="/agents/{{ agent.id }}">
                                            <div class="team-member text-center">
                                                <img src="{{ agent.image }}" alt="Image"
                                                     class="img-thumbnail rounded-circle carousel-image">
                                                <div class="text p-3">
                                                    <h2 class="mb-2 font-weight-light text-black h4">{{ agent.name }}</h2>
                                                    <span class="d-block mb-3 text-white-opacity-05">Real Estate Agent</span>

                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/agents/agents_details.html
{% extends 'base.html' %}

{%  block content %}
    <h1>{{ agent.name }}</h1>
        <img src="{{ agent.image }}" width='200px'>
    <p>{{ agent.description }}</p>
    <p>{{ agent.email }}</p>
{% endblock %}