CastleApartments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from CastleApartments import settings
from properties import views as propview
from agents import views as agentview

urlpatterns = [
    path('', propview.index, name='index'),
    path('properties/', include('properties.urls')),
    path('clients/', include('clients.urls')),
    path('agents/', include('agents.urls')),
    path('purchases/', include('purchases.urls')),
    path('admin/', admin.site.urls),
    path('about/', agentview.about, name='about'),
    path('contact/', agentview.contact, name='contact'),
]

agents/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:id>', views.get_agent_by_id, name='agent-details')
]

properties/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="properties-index"),
    path('search/', views.search, name="properties-search"),
    path('<int:id>', views.get_property_by_id, name='property-details'),
    path('create_property', views.create_property, name='create-property'),
    path('update_property/<int:id>', views.update_property, name='update-property'),
    path('email/', views.emailView, name='email'),
    path('add_images/<int:id>', views.add_images, name='add-images'),
    path('remove_image/<int:prop_id>/<int:image_id>', views.remove_image, name='remove-image')
]

properties/models.py
from django.db import models
from agents.models import Agents
from django.core.validators import MinValueValidator


class PropertiesDetails(models.Model):
    garden = models.BooleanField(blank=True)
    garage = models.BooleanField(blank=True)
    pets = models.BooleanField(blank=True)
    accessibility = models.BooleanField(blank=True)


class PropertiesAddress(models.Model):
    streetName = models.CharField(max_length=999)
    houseNumber = models.CharField(max_length=255)
    zipCode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

    def __str__(self):
        return '{} {}'.format(self.streetName, self.houseNumber)


class Properties(models.Model):
    type = models.CharField(max_length=255)
    size = models.IntegerField(validators=[MinValueValidator(1)])
    rooms = models.IntegerField(validators=[MinValueValidator(1)])
    price = models.IntegerField(validators=[MinValueValidator(50000)])
    yearBuilt = models.IntegerField(validators=[MinValueValidator(0)])
    description = models.CharField(max_length=999, blank=True)
    status = models.CharField(max_length=255, default='available')
    agent = models.ForeignKey(Agents, on_delete=models.CASCADE)
    address = models.ForeignKey(PropertiesAddress, on_delete=models.CASCADE)
    details = models.ForeignKey(PropertiesDetails, on_delete=models.CASCADE)


class PropertiesImages(models.Model):
    property = models.ForeignKey(Properties, on_delete=models.CASCADE)
    link = models.CharField(max_length=999)
    text = models.CharField(max_length=255, blank=True)

properties/forms/property_form.py
from django.forms import ModelForm, widgets
from properties.models import *

homeTypes = (
    ('house', 'House'),
    ('apartment', 'Apartment'),
    ('castle', 'Castle')
)

availability = {
    ('available', 'Available'),
    ('sold', 'Sold')
}


class PropertyUpdateForm(ModelForm):
    class Meta:
        model = Properties
        exclude = ['id', 'address', 'details']
        widgets = {
            'type': widgets.Select(attrs={'class': 'form-control'}, choices=homeTypes),
            'size': widgets.NumberInput(attrs={'class': 'form-control', 'min': 1}, ),
            'rooms': widgets.NumberInput(attrs={'class': 'form-control', 'min': 1}),
            'price': widgets.NumberInput(attrs={'class': 'form-control', 'min': 50000}),
            'yearBuilt': widgets.NumberInput(attrs={'class': 'form-control', 'min': 0}),
            'description': widgets.TextInput(attrs={'class': 'form-control'}),
            'status': widgets.Select(attrs={'class': 'form-control'}, choices=availability),
            'agent': widgets.Select(attrs={'class': 'form-control'}),
        }


class PropertyImagesUpdateForm(ModelForm):
    class Meta:
        labels = {'link': 'Image URL:', 'text': 'Image alt-text:'}
        model = PropertiesImages
        exclude = ['property']
        widgets = {
            'link': widgets.TextInput(attrs={'class': 'form-control'}),
            'text': widgets.TextInput(attrs={'class': 'form-control'})
        }


class PropertyDetailsUpdateForm(ModelForm):
    class Meta:
        model = PropertiesDetails
        exclude = ['id']
        widgets = {
            'garden': widgets.CheckboxInput(),
            'garage': widgets.CheckboxInput(),
            'accessibility': widgets.CheckboxInput(),
            'pets': widgets.CheckboxInput()
        }


class PropertyAddressUpdateForm(ModelForm):
    class Meta:
        model = PropertiesAddress
        exclude = ['id']
        widgets = {
            'streetName': widgets.TextInput(attrs={'class': 'form-control'}),
            'houseNumber': widgets.TextInput(attrs={'class': 'form-control'}),
            'zipCode': widgets.TextInput(attrs={'class': 'form-control'}),
            'city': widgets.TextInput(attrs={'class': 'form-control'}),
            'country': widgets.TextInput(attrs={'class': 'form-control'}),
        }


class PropertyImagesCreateForm(ModelForm):
    class Meta:
        labels = {'link': 'Image URL:', 'text': 'Image alt-text:'}
        model = PropertiesImages
        exclude = ['property']
        widgets = {
            'link': widgets.TextInput(attrs={'class': 'form-control'}),
            'text': widgets.TextInput(attrs={'class': 'form-control'})
        }


class PropertyDetailsCreateForm(ModelForm):
    class Meta:
        model = PropertiesDetails
        exclude = ['id']
        widgets = {
            'garden': widgets.CheckboxInput(),
            'garage': widgets.CheckboxInput(),
            'accessibility': widgets.CheckboxInput(),
            'pets': widgets.CheckboxInput()
        }


class PropertyAddressCreateForm(ModelForm):
    class Meta:
        model = PropertiesAddress
        exclude = ['id']
        widgets = {
            'streetName': widgets.TextInput(attrs={'class': 'form-control'}),
            'houseNumber': widgets.TextInput(attrs={'class': 'form-control'}),
            'zipCode': widgets.TextInput(attrs={'class': 'form-control'}),
            'city': widgets.TextInput(attrs={'class': 'form-control'}),
            'country': widgets.TextInput(attrs={'class': 'form-control'}),
        }


class PropertyCreateForm(ModelForm):
    class Meta:
        model = Properties
        exclude = ['id', 'address', 'details', 'status']
        widgets = {
            'type': widgets.Select(attrs={'class': 'form-control'}, choices=homeTypes),
            'size': widgets.NumberInput(attrs={'class': 'form-control', 'min': 1}, ),
            'rooms': widgets.NumberInput(attrs={'class': 'form-control', 'min': 1}),
            'price': widgets.NumberInput(attrs={'class': 'form-control', 'min': 50000}),
            'yearBuilt': widgets.NumberInput(attrs={'class': 'form-control', 'min': 0}),
            'description': widgets.Textarea(attrs={'class': 'form-control'}),
            'agent': widgets.Select(attrs={'class': 'form-control'})
        }

properties/forms/send_email.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

properties/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from properties.forms.property_form import *
from properties.forms.send_email import ContactForm
from properties.models import *
from agents.models import Agents
from clients.views import add_to_recently_viewed
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError


def must_be_agent(func):
    # check if user is in agents group
    # if not, return a warning message
    # else, user is permitted
    # @must_be_agent gives permission to agents
    def check_and_call(request, *args, **kwargs):
        user = request.user
        if not (user.groups.filter(name='agents').exists()):
            messages.error(request, "401 Unauthorized!")
            return redirect('index')
        return func(request, *args, **kwargs)

    return check_and_call


def get_relative_properties(request, is_agent):
    if is_agent is True:
        properties = Properties.objects.all()
    else:
        properties = Properties.objects.filter(status="available")
    return properties


def index(request):
    is_agent = request.user.groups.filter(name="agents").exists()
    properties = get_relative_properties(request, is_agent)
    context = {
        'properties': properties,
        'agents': Agents.objects.all(),
        'property_types': Properties.objects.distinct('type'),
        'property_zipcodes': Properties.objects.distinct('address__zipCode'),
        'property_countries': Properties.objects.distinct('address__country'),
        'property_cities': Properties.objects.distinct('address__city'),
        'is_agent': is_agent
    }
    return render(request, 'properties/index.html', context)


def search(request):
    # if 'search filter' in the url get the value
    # then filter the objects with the matching ones
    # then continue, if 'type' in the url...

    template = 'properties/index.html'

    if 'search_filter' in request.GET:
        search_filter = request.GET['search_filter']
        is_agent = request.user.groups.filter(name='agents').exists()
        if is_agent is False:
            properties = Properties.objects.filter(description__icontains=search_filter).filter(status='available')
        else:
            properties = Properties.objects.filter(description__icontains=search_filter)

        if 'type' in request.GET:
            house_type = request.GET['type']
            properties = properties.filter(type=house_type)

        if 'status' in request.GET:
            status = request.GET['status']
            properties = properties.filter(status=status)

        if 'city' in request.GET:
            city = request.GET['city']
            properties = properties.filter(address__city__icontains=city)

        if 'country' in request.GET:
            country = request.GET['country']
            properties = properties.filter(address__country__icontains=country)

        if 'rooms' in request.GET:
            rooms = request.GET['rooms']
            properties = properties.filter(rooms__lte=rooms)

        if 'size' in request.GET:
            size = request.GET['size']
            properties = properties.filter(size=size)

        if 'zipcode' in request.GET:
            zipcode = request.GET['zipcode']
            properties = properties.filter(address__zipCode=zipcode)

        if 'price' in request.GET:
            price = request.GET['price']
            properties = properties.filter(price__range=[50000, price])

        if 'garage' in request.GET:
            properties = properties.filter(details__garage=True)

        if 'garden' in request.GET:
            properties = properties.filter(details__garden=True)

        if 'accessibility' in request.GET:
            properties = properties.filter(details__accessibility=True)

        if 'pets' in request.GET:
            properties = properties.filter(details__pets=True)

        if 'orderbyname' in request.GET:
            properties = properties.order_by('address__streetName')

        if 'orderbyprice' in request.GET:
            properties = properties.order_by('price')

        properties = [{
            'id': x.id,
            'firstImage': x.propertiesimages_set.first().link,
            'altText': x.propertiesimages_set.first().text,
            'price': x.price,
            'streetName': x.address.streetName,
            'houseNumber': x.address.houseNumber,
            'city': x.address.city,
            'country': x.address.country,
            'zipCode': x.address.zipCode,
            'size': x.size,
            'rooms': x.rooms,
            'yearBuilt': x.yearBuilt,
            'status': x.status,
            'type': x.type
        } for x in properties]

        return JsonResponse({'data': properties})

    context = {'properties': Properties.objects.all()}
    return render(request, template, context)


def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
        return form
    elif request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['castle_apartments@hotmail.com'])
                messages.success(request, 'Success, email sent')
            except BadHeaderError:
                messages.error(request, "Something went wrong, email wasn't sent")


def get_property_by_id(request, id):
    is_agent = request.user.groups.filter(name="agents").exists()
    email = emailView(request)
    if request.user.is_authenticated and is_agent is False:
        add_to_recently_viewed(request, id)
    return render(request, 'properties/property_details.html', {
        'property': get_object_or_404(Properties, pk=id),
        'is_agent': is_agent,
        'email': email
    })


def order_property_by_name(request):
    template = 'properties/index.html'
    properties_name = {'properties': Properties.objects.all().order_by('address__properties')}
    return render(request, template, properties_name)


@must_be_agent
def create_property(request):
    is_agent = request.user.groups.filter(name="agents").exists()
    if request.method == 'POST':
        propForm = PropertyCreateForm(data=request.POST)
        propAddressForm = PropertyAddressCreateForm(data=request.POST)
        propDetailsForm = PropertyDetailsCreateForm(data=request.POST)
        propImagesForm = PropertyImagesCreateForm(data=request.POST)
        if (propAddressForm.is_valid()
                and propDetailsForm.is_valid()):
            propAddress = propAddressForm.save()
            propDetails = propDetailsForm.save()
            prop = propForm.save(commit=False)
            prop.address = propAddress
            prop.details = propDetails
            if (propForm.is_valid()):
                prop.save()
                propImages = propImagesForm.save(commit=False)
                propImages.property = prop
                if (propImagesForm.is_valid()):
                    propImages.save()
                    messages.success(request, 'Property created successfully')
                    return redirect('property-details', prop.id)
                else:
                    messages.error(request, 'Property cannot be created. Please try again.')
    else:
        context = {
            'propertyForm': PropertyCreateForm(),
            'propertyAddressForm': PropertyAddressCreateForm(),
            'propertyDetailsForm': PropertyDetailsCreateForm(),
            'propertyImagesForm': PropertyImagesCreateForm(),
            'is_agent': is_agent
        }
        return render(request, 'properties/create_property.html', context)


@must_be_agent
def update_property(request, id):
    is_agent = request.user.groups.filter(name="agents").exists()
    prop = Properties.objects.filter(pk=id).first()
    details = prop.details
    address = prop.address
    image = PropertiesImages.objects.filter(property=id).first()
    if request.method == 'POST':
        propForm = PropertyUpdateForm(instance=prop, data=request.POST)
        propAddressForm = PropertyAddressUpdateForm(instance=address, data=request.POST)
        propDetailsForm = PropertyDetailsUpdateForm(instance=details, data=request.POST)
        propMainImageForm = PropertyImagesUpdateForm(instance=image, data=request.POST)
        if (propAddressForm.is_valid()
                and propDetailsForm.is_valid()):
            propAddress = propAddressForm.save()
            propDetails = propDetailsForm.save()
            prop = propForm.save(commit=False)
            prop.address = propAddress
            prop.details = propDetails
            if (propForm.is_valid()):
                prop.save()
                propImages = propMainImageForm.save(commit=False)
                propImages.property = prop
                if (propMainImageForm.is_valid()):
                    propImages.save()
                    messages.success(request, 'Property updated successfully.')
                    return redirect('property-details', id=id)
        else:
            messages.error(request, 'Property cannot be updated. Please try again.')
            return redirect('property-details', id=id)
    else:
        context = {
            'propertyForm': PropertyUpdateForm(instance=prop),
            'propertyAddressForm': PropertyAddressUpdateForm(instance=address),
            'propertyDetailsForm': PropertyDetailsUpdateForm(instance=details),
            'propertyImagesForm': PropertyImagesUpdateForm(instance=image),
            'is_agent': is_agent
        }
        return render(request, 'properties/update_property.html', context)


@must_be_agent
def add_images(request, id):
    is_agent = request.user.groups.filter(name="agents").exists()
    prop = Properties.objects.filter(pk=id).first()

templates/properties/add_images.html
{% extends "base.html" %}
{% block content %}
    <div class="site-section">
        <div class="container">
            {% if is_agent %}
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <label for="{{ field.id_for_label }}">Image {{ field.name|capfirst }}:</label>
                        {{ field.as_widget }}
                    {% endfor %}
                    <br>
                    <div class="float-lg-right">
                        <a id="{{ property.id }}" href="/properties/{{ property.id }}"
                           class="btn btn-danger btn-lg">Back to Property</a>
                        <input type="submit" value="Add Image" class="btn btn-primary btn-lg"/>
                    </div>
                </form>
                <div class="row mt-5">
                    <div class="col-12">
                        <h2 class="h4 text-black mb-3">Property Gallery</h2>
                    </div>
                    {% for image in property.propertiesimages_set.all %}
                        <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                            <a href="{% url 'remove-image' property.id image.id %}">X</a>
                            <a href="{{ image.link }}" class="image-popup gal-item"><img src="{{ image.link }}"
                                                                                         alt="{{ image.text }}"
                                                                                         class="img-fluid gallery-image"></a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h1>401 Unauthorized</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/properties/create_property.html
{% extends "base.html" %}
{% block content %}
    <div class="site-section">
        <div class="container">
            {% if is_agent %}
                <form method="post">
                    {% csrf_token %}
                    {{ propertyForm }}
                    <p>Details:</p>
                    <ul class="list-group">
                        {% for field in propertyDetailsForm %}
                            <li class="list-group-item">
                                <label for="{{ field.id_for_label }}">{{ field.label|capfirst }}:</label>
                                {{ field.as_widget }}
                            </li>
                        {% endfor %}
                    </ul>
                    {{ propertyAddressForm }}
                    {% for field in propertyImagesForm %}
                        <label for="{{ field.id_for_label }}">Main Image {{ field.name|capfirst }}:</label>
                        {{ field.as_widget }}
                    {% endfor %}
                    <br>
                    <input type="submit" value="Create Property" class="btn btn-primary btn-lg"/>
                </form>
            {% else %}
                <h1>401 Unauthorized</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/properties/property_details.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    {% if property.propertiesimages_set.first.link %}
        <div class="site-blocks-cover overlay"
             style="background-image: url({{ property.propertiesimages_set.first.link }});" data-aos="fade"
             data-stellar-background-ratio="0.5">
    {% else %}
        <div class="site-blocks-cover overlay"
             style="background-image: url(https://via.placeholder.com/800x450.png?text=No+Image+Found);" data-aos="fade"
             data-stellar-background-ratio="0.5">
    {% endif %}
<div class="container">
    <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-10">
            <span class="d-inline-block text-white px-3 mb-3 property-offer-type rounded">Property Details of</span>
            <h1 class="mb-2">{{ property.address.streetName }} {{ property.address.houseNumber }}</h1>
            <p class="mb-5"><strong class="h2 text-success font-weight-bold"
                                    id="price1">{{ property.price|intcomma }}
                ISK</strong>
            </p>
        </div>
    </div>
</div>
</div>

    <div class="site-section site-section-sm">
        <div class="container">
            <div class="row">
                <div class="col-lg-8" style="margin-top: -150px;">
                    <div class="mb-5">
                        <div class="slide-one-item home-slider owl-carousel">
                            {% if property.propertiesimages_set.first.link %}
                                {% for image in property.propertiesimages_set.all %}
                                    <div>
                                        <img src="{{ image.link }}" alt="{{ image.text }}"
                                             class="img-thumbnail property-images">
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div>
                                    <img src="https://via.placeholder.com/800x450.png?text=No+Image+Found"
                                         alt="No Image Found"
                                         class="img-thumbnail">
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div>
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <strong class="text-success h1 mb-3" id="price2">{{ property.price|intcomma }}
                                    ISK</strong>
                                <select name="offer-types" id="currency" class="form-control rounded">
                                    <option value="ISK">ISK</option>
                                    <option value="USD">USD</option>
                                    <option value="EUR">EUR</option>
                                    <option value="GBP">GBP</option>
                                    <option value="JPY">JPY</option>
                                    <option value="NOK">NOK</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <ul class="property-specs-wrap mb-3 mb-lg-0  float-lg-right">
                                    <li>
                                        <span class="property-specs">Rooms</span>
                                        <span class="property-specs-number">{{ property.rooms }}</span>
                                    </li>
                                    <li>
                                        <span class="property-specs">m<sup>2</sup></span>
                                        <span class="property-specs-number">{{ property.size }}</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6 col-lg-4 text-left border-bottom border-top py-3">
                                <span class="d-inline-block text-black mb-0 caption-text">Home Type</span>
                                <strong class="d-block">{{ property.type|upper }}</strong>
                            </div>
                            <div class="col-md-6 col-lg-4 text-left border-bottom border-top py-3">
                                <span class="d-inline-block text-black mb-0 caption-text">Year Built</span>
                                <strong class="d-block">{{ property.yearBuilt }}</strong>
                            </div>
                            <div class="col-md-6 col-lg-4 text-left border-bottom border-top py-3">
                                {% if is_agent %}
                                    <a href="{% url "update-property" property.id %}"
                                       class="btn btn-primary btn-lg btn-block">Edit Property</a>
                                {% else %}
                                    {% if property.status == 'available' %}
                                        <a href="{% url "purchase" property.id %}"
                                           class="btn btn-primary btn-lg btn-block">Purchase</a>
                                    {% else %}
                                        <a class="btn btn-primary btn-lg btn-block disabled">Sold</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                        <h2 class="h4 text-black">More Info</h2>
                        <p>{{ property.description }}</p>

                        <div class="row mt-5">
                            <div class="col-12">
                                <h2 class="h4 text-black mb-3">Property Gallery</h2>
                            </div>
                            {% for image in property.propertiesimages_set.all %}
                                <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                                    <a href="{{ image.link }}" class="image-popup gal-item"><img src="{{ image.link }}"
                                                                                                 alt="{{ image.text }}"
                                                                                                 class="img-fluid gallery-image"></a>
                                </div>
                            {% endfor %}
                            {% if is_agent %}
                                <a href="{% url "add-images" property.id %}"
                                   class="btn btn-primary btn-lg btn-block">Add & Remove Images</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 pl-md-5">

                    <div class="bg-white widget border rounded">
                        <h4 class="h4 text-black widget-title mb-3">Agent Name:</h4>
                        <p>{{ property.agent.name }}</p>
                        <img src="{{ property.agent.image }}" height="200px" class="img-thumbnail"/>
                        <div class="form-group">
                            <form method="post">
                                {% csrf_token %}
                                <h4 class="form-header">Send me a message</h4>
                                <div class="form-group">
                                    <label for="id_from_email">Email:</label>
                                    <input class="form-control" name="from_email" type="text" id="id_from_email"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label for="id_subject">Subject:</label>
                                    <input class="form-control" name="subject" type="text" id="id_subject" required>
                                </div>
                                <div class="form-group">
                                    <label for="id_message">Message:</label>
                                    <textarea class="form-control" name="message" cols="40" rows="10"
                                              id="id_message" required></textarea>
                                </div>
                                <br>
                                <input type="submit" id="send" class="btn btn-primary" value="Send Message">
                            </form>
                        </div>
                    </div>

                    <div class="bg-white widget border rounded">
                        <h3 class="h4 text-black widget-title mb-3">Paragraph</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit qui explicabo, libero nam,
                            saepe eligendi. Molestias maiores illum error rerum. Exercitationem ullam saepe, minus,
                            reiciendis ducimus quis. Illo, quisquam, veritatis.</p>
                    </div>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/properties/single_property.html
<div class="card" style="width: 18rem;">

    <a href="#">
        <img class="card-img-top" src="{{ property.propertiesimages_set.first.link }}" width="200px"
             alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ property.address }}</h5>
            <p class="card-text">{{ property.price }}</p>
        </div>
    </a>
</div>
<a href="#">
    <img class="card-img-top" src="{{ property.propertiesimages_set.first.link }}" width="200px"
         alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">{{ property.address }}</h5>
        <p class="card-text">{{ property.price }}</p>
    </div>
</a>
</div>